export const LOADING = 'LOADING';
export const LOAD_SOCIALS_SUCCESS = 'LOAD_SOCIALS_SUCCESS';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';